In [2]:
print("hello world")

hello world

In [3]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Pakistan Largest Ecommerce Dataset.csv.zip to Pakistan Largest Ecommerce Dataset.csv.zip

In [5]:
orders = pd.read_csv("Pakistan Largest Ecommerce Dataset.csv.zip")

/tmp/ipykernel_1052/2063883264.py:1: DtypeWarning: Columns (1,2,3,7,8,9,11,12,13,14,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  orders = pd.read_csv("Pakistan Largest Ecommerce Dataset.csv.zip")

In [6]:
# display 1st 10
first_ten = orders.head(10)

print("1st Ten records:", first_ten)

1st Ten records:     item_id          status created_at  \
0  211131.0        complete   7/1/2016
1  211133.0        canceled   7/1/2016
2  211134.0        canceled   7/1/2016
3  211135.0        complete   7/1/2016
4  211136.0  order_refunded   7/1/2016
5  211137.0        canceled   7/1/2016
6  211138.0        complete   7/1/2016
7  211139.0        complete   7/1/2016
8  211140.0        canceled   7/1/2016
9  211141.0        canceled   7/1/2016

                                                 sku    price  qty_ordered  \
0                                  kreations_YI 06-L   1950.0          1.0
1  kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...    240.0          1.0
2                                 Ego_UP0017-999-MR0   2450.0          1.0
3                                     kcc_krone deal    360.0          1.0
4                                        BK7010400AG    555.0          2.0
5                      UK_Namkino All In One 200 Gms     80.0          1.0
6                                     kcc_krone deal    360.0          1.0
7                       UK_Namkino Mix Nimco 400 Gms    170.0          1.0
8                               Apple iPhone 6S 64GB  96499.0          1.0
9                               Apple iPhone 6S 64GB  96499.0          1.0

   grand_total increment_id    category_name_1 sales_commission_code  ...  \
0       1950.0    100147443    Women's Fashion                    \N  ...
1        240.0    100147444  Beauty & Grooming                    \N  ...
2       2450.0    100147445    Women's Fashion                    \N  ...
3         60.0    100147446  Beauty & Grooming           R-FSD-52352  ...
4       1110.0    100147447            Soghaat                    \N  ...
5         80.0    100147448            Soghaat                    \N  ...
6         60.0    100147449  Beauty & Grooming                    \N  ...
7        170.0    100147450            Soghaat                    \N  ...
8      96499.0    100147451  Mobiles & Tablets                    \N  ...
9      96499.0    100147452  Mobiles & Tablets                    \N  ...

   Month Customer Since     M-Y    FY Customer ID  Unnamed: 21  Unnamed: 22  \
0    7.0         2016-7  7-2016  FY17         1.0          NaN          NaN
1    7.0         2016-7  7-2016  FY17         2.0          NaN          NaN
2    7.0         2016-7  7-2016  FY17         3.0          NaN          NaN
3    7.0         2016-7  7-2016  FY17         4.0          NaN          NaN
4    7.0         2016-7  7-2016  FY17         5.0          NaN          NaN
5    7.0         2016-7  7-2016  FY17         6.0          NaN          NaN
6    7.0         2016-7  7-2016  FY17         7.0          NaN          NaN
7    7.0         2016-7  7-2016  FY17         6.0          NaN          NaN
8    7.0         2016-7  7-2016  FY17         8.0          NaN          NaN
9    7.0         2016-7  7-2016  FY17         8.0          NaN          NaN

  Unnamed: 23 Unnamed: 24 Unnamed: 25
0         NaN         NaN         NaN
1         NaN         NaN         NaN
2         NaN         NaN         NaN
3         NaN         NaN         NaN
4         NaN         NaN         NaN
5         NaN         NaN         NaN
6         NaN         NaN         NaN
7         NaN         NaN         NaN
8         NaN         NaN         NaN
9         NaN         NaN         NaN

[10 rows x 26 columns]

In [7]:
# last 10
last_ten = orders.tail(10)

print("Last Ten records:", last_ten)

Last Ten records:          item_id status created_at  sku  price  qty_ordered  grand_total  \
1048565      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048566      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048567      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048568      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048569      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048570      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048571      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048572      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048573      NaN    NaN        NaN  NaN    NaN          NaN          NaN
1048574      NaN    NaN        NaN  NaN    NaN          NaN          NaN

        increment_id category_name_1 sales_commission_code  ...  Month  \
1048565          NaN             NaN                   NaN  ...    NaN
1048566          NaN             NaN                   NaN  ...    NaN
1048567          NaN             NaN                   NaN  ...    NaN
1048568          NaN             NaN                   NaN  ...    NaN
1048569          NaN             NaN                   NaN  ...    NaN
1048570          NaN             NaN                   NaN  ...    NaN
1048571          NaN             NaN                   NaN  ...    NaN
1048572          NaN             NaN                   NaN  ...    NaN
1048573          NaN             NaN                   NaN  ...    NaN
1048574          NaN             NaN                   NaN  ...    NaN

        Customer Since  M-Y   FY Customer ID  Unnamed: 21  Unnamed: 22  \
1048565            NaN  NaN  NaN         NaN          NaN          NaN
1048566            NaN  NaN  NaN         NaN          NaN          NaN
1048567            NaN  NaN  NaN         NaN          NaN          NaN
1048568            NaN  NaN  NaN         NaN          NaN          NaN
1048569            NaN  NaN  NaN         NaN          NaN          NaN
1048570            NaN  NaN  NaN         NaN          NaN          NaN
1048571            NaN  NaN  NaN         NaN          NaN          NaN
1048572            NaN  NaN  NaN         NaN          NaN          NaN
1048573            NaN  NaN  NaN         NaN          NaN          NaN
1048574            NaN  NaN  NaN         NaN          NaN          NaN

        Unnamed: 23 Unnamed: 24 Unnamed: 25
1048565         NaN         NaN         NaN
1048566         NaN         NaN         NaN
1048567         NaN         NaN         NaN
1048568         NaN         NaN         NaN
1048569         NaN         NaN         NaN
1048570         NaN         NaN         NaN
1048571         NaN         NaN         NaN
1048572         NaN         NaN         NaN
1048573         NaN         NaN         NaN
1048574         NaN         NaN         NaN

[10 rows x 26 columns]

In [8]:
# total no. of rows & columns
rows_columns = orders.shape
print("Total no. of rows & columns:", rows_columns)

Total no. of rows & columns: (1048575, 26)

In [9]:
# columns name
columns = orders.columns
for column in columns:
  print(column)

item_id
status
created_at
sku
price
qty_ordered
grand_total
increment_id
category_name_1
sales_commission_code
discount_amount
payment_method
Working Date
BI Status
 MV
Year
Month
Customer Since
M-Y
FY
Customer ID
Unnamed: 21
Unnamed: 22
Unnamed: 23
Unnamed: 24
Unnamed: 25

In [10]:
# column data types

orders.dtypes

item_id                  float64
status                    object
created_at                object
sku                       object
price                    float64
qty_ordered              float64
grand_total              float64
increment_id              object
category_name_1           object
sales_commission_code     object
discount_amount          float64
payment_method            object
Working Date              object
BI Status                 object
 MV                       object
Year                     float64
Month                    float64
Customer Since            object
M-Y                       object
FY                        object
Customer ID              float64
Unnamed: 21              float64
Unnamed: 22              float64
Unnamed: 23              float64
Unnamed: 24              float64
Unnamed: 25              float64
dtype: object

In [11]:
print("Numerical columns:")
print(orders.select_dtypes(include="number").columns)

Numerical columns:
Index(['item_id', 'price', 'qty_ordered', 'grand_total', 'discount_amount',
       'Year', 'Month', 'Customer ID', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [12]:
print("Text columns:")
print(orders.select_dtypes(include="object").columns)

Text columns:
Index(['status', 'created_at', 'sku', 'increment_id', 'category_name_1',
       'sales_commission_code', 'payment_method', 'Working Date', 'BI Status',
       ' MV ', 'Customer Since', 'M-Y', 'FY'],
      dtype='object')

In [13]:
print("Date/Time columns:")
print(orders.select_dtypes(include="datetime").columns)

Date/Time columns:
Index([], dtype='object')

In [14]:
print(orders.columns)

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', ' MV ', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')

In [15]:
price = orders["price"]
qty_ordered = orders["qty_ordered"]
payment_method = orders["payment_method"]
category_name_1 = orders["category_name_1"]

print("price")
print("qty_ordered")
print("payment_method")
print("category_name_1")

price
qty_ordered
payment_method
category_name_1

In [16]:
# display 1st 10 values
print("Price: ", price.head(10))
print("Quantity of order: ", qty_ordered.head(10))
print("Payment method: ", payment_method.head(10))
print("Category name: ", category_name_1.head(10))

Price:  0     1950.0
1      240.0
2     2450.0
3      360.0
4      555.0
5       80.0
6      360.0
7      170.0
8    96499.0
9    96499.0
Name: price, dtype: float64
Quantity of order:  0    1.0
1    1.0
2    1.0
3    1.0
4    2.0
5    1.0
6    1.0
7    1.0
8    1.0
9    1.0
Name: qty_ordered, dtype: float64
Payment method:  0              cod
1              cod
2              cod
3              cod
4              cod
5              cod
6              cod
7              cod
8    ublcreditcard
9        mygateway
Name: payment_method, dtype: object
Category name:  0      Women's Fashion
1    Beauty & Grooming
2      Women's Fashion
3    Beauty & Grooming
4              Soghaat
5              Soghaat
6    Beauty & Grooming
7              Soghaat
8    Mobiles & Tablets
9    Mobiles & Tablets
Name: category_name_1, dtype: object

In [17]:
# total number of orders
print("Total Orders:", orders["item_id"].count())
print("Total Quantity:", orders["qty_ordered"].sum())
print("Average Product Price:", orders["price"].mean())
print("Maximum Product Price:", orders["price"].max())
print("Minimum Product Price:", orders["price"].min())

Total Orders: 584524
Total Quantity: 757770.0
Average Product Price: 6348.7475310337995
Maximum Product Price: 1012625.9
Minimum Product Price: 0.0

In [18]:
# total number of missing values in every column
orders.isnull().sum()

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [19]:
# columns that contain null values
missing_values = orders.isnull().sum()
print(missing_values[missing_values > 0])

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [20]:
# percentage of missing values for every column
missing_count = orders.isnull().sum()
missing_percentage = (missing_count / len(orders)) * 100

In [21]:
missing_report = pd.DataFrame({
    "Column Name": orders.columns,
    "Missing Count": missing_count.values,
    "Missing Percentage": missing_percentage.values
})

print(missing_report)

              Column Name  Missing Count  Missing Percentage
0                 item_id         464051           44.255394
1                  status         464066           44.256825
2              created_at         464051           44.255394
3                     sku         464071           44.257302
4                   price         464051           44.255394
5             qty_ordered         464051           44.255394
6             grand_total         464051           44.255394
7            increment_id         464051           44.255394
8         category_name_1         464215           44.271034
9   sales_commission_code         601229           57.337720
10        discount_amount         464051           44.255394
11         payment_method         464051           44.255394
12           Working Date         464051           44.255394
13              BI Status         464051           44.255394
14                    MV          464051           44.255394
15                   Year         464051           44.255394
16                  Month         464051           44.255394
17         Customer Since         464062           44.256443
18                    M-Y         464051           44.255394
19                     FY         464051           44.255394
20            Customer ID         464062           44.256443
21            Unnamed: 21        1048575          100.000000
22            Unnamed: 22        1048575          100.000000
23            Unnamed: 23        1048575          100.000000
24            Unnamed: 24        1048575          100.000000
25            Unnamed: 25        1048575          100.000000

In [22]:
# copy of original dataframe
original_orders = orders.copy()
# cleaned dataframe
cleaned_orders = orders.fillna(0)

In [23]:
cleaned_orders

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,0.0,0.0,0.0,0.0,0.0
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,0.0,0.0,0.0,0.0,0.0
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,0.0,0.0,0.0,0.0,0.0
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,0.0,0.0,0.0,0.0,0.0
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,0.0,0,0,0,0.0,0.0,0.0,0,0,0,...,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1048571,0.0,0,0,0,0.0,0.0,0.0,0,0,0,...,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1048572,0.0,0,0,0,0.0,0.0,0.0,0,0,0,...,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1048573,0.0,0,0,0,0.0,0.0,0.0,0,0,0,...,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1048574,0.0,0,0,0,0.0,0.0,0.0,0,0,0,...,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
print("Rows before cleaning:", len(original_orders))
print("Rows after cleaning:", len(cleaned_orders))
print("Missing values before cleaning:", original_orders.isnull().sum().sum())
print("Missing values after cleaning:", cleaned_orders.isnull().sum().sum())

Rows before cleaning: 1048575
Rows after cleaning: 1048575
Missing values before cleaning: 15125345
Missing values after cleaning: 0

In [25]:
# combine categories
orders_part1 = orders[orders["category_name_1"] == "Electronics"]
orders_part2 = orders[orders["category_name_1"] == "Fashion"]
combined_products = pd.concat([orders_part1, orders_part2])

print(combined_products)

Empty DataFrame
Columns: [item_id, status, created_at, sku, price, qty_ordered, grand_total, increment_id, category_name_1, sales_commission_code, discount_amount, payment_method, Working Date, BI Status,  MV , Year, Month, Customer Since, M-Y, FY, Customer ID, Unnamed: 21, Unnamed: 22, Unnamed: 23, Unnamed: 24, Unnamed: 25]
Index: []

[0 rows x 26 columns]

In [27]:
# combine horizontally
order1 = orders[["item_id", "price"]]
order2 = orders[["qty_ordered", "payment_method"]]

combined_orders = pd.concat([order1, order2], axis=1)

print(combined_orders.head())

    item_id   price  qty_ordered payment_method
0  211131.0  1950.0          1.0            cod
1  211133.0   240.0          1.0            cod
2  211134.0  2450.0          1.0            cod
3  211135.0   360.0          1.0            cod
4  211136.0   555.0          2.0            cod

In [28]:
customers = orders[['Customer ID']].drop_duplicates()
orders1 = orders.copy()
print(customers.head())
print(orders1.head())

   Customer ID
0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
    item_id          status created_at  \
0  211131.0        complete   7/1/2016
1  211133.0        canceled   7/1/2016
2  211134.0        canceled   7/1/2016
3  211135.0        complete   7/1/2016
4  211136.0  order_refunded   7/1/2016

                                                 sku   price  qty_ordered  \
0                                  kreations_YI 06-L  1950.0          1.0
1  kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...   240.0          1.0
2                                 Ego_UP0017-999-MR0  2450.0          1.0
3                                     kcc_krone deal   360.0          1.0
4                                        BK7010400AG   555.0          2.0

   grand_total increment_id    category_name_1 sales_commission_code  ...  \
0       1950.0    100147443    Women's Fashion                    \N  ...
1        240.0    100147444  Beauty & Grooming                    \N  ...
2       2450.0    100147445    Women's Fashion                    \N  ...
3         60.0    100147446  Beauty & Grooming           R-FSD-52352  ...
4       1110.0    100147447            Soghaat                    \N  ...

   Month Customer Since     M-Y    FY Customer ID  Unnamed: 21  Unnamed: 22  \
0    7.0         2016-7  7-2016  FY17         1.0          NaN          NaN
1    7.0         2016-7  7-2016  FY17         2.0          NaN          NaN
2    7.0         2016-7  7-2016  FY17         3.0          NaN          NaN
3    7.0         2016-7  7-2016  FY17         4.0          NaN          NaN
4    7.0         2016-7  7-2016  FY17         5.0          NaN          NaN

  Unnamed: 23 Unnamed: 24 Unnamed: 25
0         NaN         NaN         NaN
1         NaN         NaN         NaN
2         NaN         NaN         NaN
3         NaN         NaN         NaN
4         NaN         NaN         NaN

[5 rows x 26 columns]

In [29]:
# inner merge
inner_merged = pd.merge(customers, orders1, on='Customer ID', how='inner')

print(inner_merged)
print("Number of records:", len(inner_merged))

         Customer ID   item_id      status  created_at  \
0                1.0  211131.0    complete    7/1/2016
1                2.0  211133.0    canceled    7/1/2016
2                2.0  324257.0    canceled  11/25/2016
3                3.0  211134.0    canceled    7/1/2016
4                3.0  473369.0    complete   5/19/2017
...              ...       ...         ...         ...
1048570     115323.0  905179.0        paid   8/28/2018
1048571     115324.0  905191.0         cod   8/28/2018
1048572     115325.0  905200.0         cod   8/28/2018
1048573     115325.0  905202.0         cod   8/28/2018
1048574     115326.0  905205.0  processing   8/28/2018

                                                       sku    price  \
0                                        kreations_YI 06-L   1950.0
1        kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...    240.0
2                                      RS_Habshi Halwa Tin    270.0
3                                       Ego_UP0017-999-MR0   2450.0
4                                                BT_BT-422    530.0
...                                                    ...      ...
1048570                                APPCHA5AF14939B8F8A  44199.0
1048571                                MEFCOT5A8D1E973B886    399.0
1048572                              WOFVAL59D5EA84167F9-M    400.0
1048573                              WOFNIG5B4D7EB0E9FDD-L    499.0
1048574                                MATHUA5AF70A7D1E50A  35599.0

         qty_ordered  grand_total increment_id    category_name_1  ...  \
0                1.0       1950.0    100147443    Women's Fashion  ...
1                1.0        240.0    100147444  Beauty & Grooming  ...
2                1.0        270.0    100222998            Soghaat  ...
3                1.0       2450.0    100147445    Women's Fashion  ...
4                1.0       1245.0    100306394      Men's Fashion  ...
...              ...          ...          ...                ...  ...
1048570          1.0      44499.0    100562365         Appliances  ...
1048571          1.0        549.0    100562376      Men's Fashion  ...
1048572          1.0        550.0    100562383    Women's Fashion  ...
1048573          1.0        649.0    100562384    Women's Fashion  ...
1048574          1.0      35899.0    100562386  Mobiles & Tablets  ...

           Year  Month Customer Since      M-Y    FY Unnamed: 21  Unnamed: 22  \
0        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
1        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
2        2016.0   11.0         2016-7  11-2016  FY17         NaN          NaN
3        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
4        2017.0    5.0         2016-7   5-2017  FY17         NaN          NaN
...         ...    ...            ...      ...   ...         ...          ...
1048570  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048571  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048572  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048573  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048574  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN

         Unnamed: 23 Unnamed: 24 Unnamed: 25
0                NaN         NaN         NaN
1                NaN         NaN         NaN
2                NaN         NaN         NaN
3                NaN         NaN         NaN
4                NaN         NaN         NaN
...              ...         ...         ...
1048570          NaN         NaN         NaN
1048571          NaN         NaN         NaN
1048572          NaN         NaN         NaN
1048573          NaN         NaN         NaN
1048574          NaN         NaN         NaN

[1048575 rows x 26 columns]
Number of records: 1048575

In [30]:
# left merge
left_merged = pd.merge(customers, orders1, on='Customer ID', how='left')

print(left_merged)
print("Number of records:", len(left_merged))

         Customer ID   item_id      status  created_at  \
0                1.0  211131.0    complete    7/1/2016
1                2.0  211133.0    canceled    7/1/2016
2                2.0  324257.0    canceled  11/25/2016
3                3.0  211134.0    canceled    7/1/2016
4                3.0  473369.0    complete   5/19/2017
...              ...       ...         ...         ...
1048570     115323.0  905179.0        paid   8/28/2018
1048571     115324.0  905191.0         cod   8/28/2018
1048572     115325.0  905200.0         cod   8/28/2018
1048573     115325.0  905202.0         cod   8/28/2018
1048574     115326.0  905205.0  processing   8/28/2018

                                                       sku    price  \
0                                        kreations_YI 06-L   1950.0
1        kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...    240.0
2                                      RS_Habshi Halwa Tin    270.0
3                                       Ego_UP0017-999-MR0   2450.0
4                                                BT_BT-422    530.0
...                                                    ...      ...
1048570                                APPCHA5AF14939B8F8A  44199.0
1048571                                MEFCOT5A8D1E973B886    399.0
1048572                              WOFVAL59D5EA84167F9-M    400.0
1048573                              WOFNIG5B4D7EB0E9FDD-L    499.0
1048574                                MATHUA5AF70A7D1E50A  35599.0

         qty_ordered  grand_total increment_id    category_name_1  ...  \
0                1.0       1950.0    100147443    Women's Fashion  ...
1                1.0        240.0    100147444  Beauty & Grooming  ...
2                1.0        270.0    100222998            Soghaat  ...
3                1.0       2450.0    100147445    Women's Fashion  ...
4                1.0       1245.0    100306394      Men's Fashion  ...
...              ...          ...          ...                ...  ...
1048570          1.0      44499.0    100562365         Appliances  ...
1048571          1.0        549.0    100562376      Men's Fashion  ...
1048572          1.0        550.0    100562383    Women's Fashion  ...
1048573          1.0        649.0    100562384    Women's Fashion  ...
1048574          1.0      35899.0    100562386  Mobiles & Tablets  ...

           Year  Month Customer Since      M-Y    FY Unnamed: 21  Unnamed: 22  \
0        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
1        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
2        2016.0   11.0         2016-7  11-2016  FY17         NaN          NaN
3        2016.0    7.0         2016-7   7-2016  FY17         NaN          NaN
4        2017.0    5.0         2016-7   5-2017  FY17         NaN          NaN
...         ...    ...            ...      ...   ...         ...          ...
1048570  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048571  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048572  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048573  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN
1048574  2018.0    8.0         2018-8   8-2018  FY19         NaN          NaN

         Unnamed: 23 Unnamed: 24 Unnamed: 25
0                NaN         NaN         NaN
1                NaN         NaN         NaN
2                NaN         NaN         NaN
3                NaN         NaN         NaN
4                NaN         NaN         NaN
...              ...         ...         ...
1048570          NaN         NaN         NaN
1048571          NaN         NaN         NaN
1048572          NaN         NaN         NaN
1048573          NaN         NaN         NaN
1048574          NaN         NaN         NaN

[1048575 rows x 26 columns]
Number of records: 1048575

In [31]:
# compare merges
print("Inner merge rows:", len(inner_merged))
print("Left merge rows:", len(left_merged))

print("Records not matched:", len(left_merged) - len(inner_merged))

Inner merge rows: 1048575
Left merge rows: 1048575
Records not matched: 0

In [32]:
# join customer and df1 data
# Join customer and order data
customer_data = customers.set_index('Customer ID')
order_data = orders1.set_index('Customer ID')

joined_data = customer_data.join(order_data, how='inner')

print(joined_data)

              item_id      status  created_at  \
Customer ID
1.0          211131.0    complete    7/1/2016
2.0          211133.0    canceled    7/1/2016
2.0          324257.0    canceled  11/25/2016
3.0          211134.0    canceled    7/1/2016
3.0          473369.0    complete   5/19/2017
...               ...         ...         ...
115323.0     905179.0        paid   8/28/2018
115324.0     905191.0         cod   8/28/2018
115325.0     905200.0         cod   8/28/2018
115325.0     905202.0         cod   8/28/2018
115326.0     905205.0  processing   8/28/2018

                                                           sku    price  \
Customer ID
1.0                                          kreations_YI 06-L   1950.0
2.0          kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...    240.0
2.0                                        RS_Habshi Halwa Tin    270.0
3.0                                         Ego_UP0017-999-MR0   2450.0
3.0                                                  BT_BT-422    530.0
...                                                        ...      ...
115323.0                                   APPCHA5AF14939B8F8A  44199.0
115324.0                                   MEFCOT5A8D1E973B886    399.0
115325.0                                 WOFVAL59D5EA84167F9-M    400.0
115325.0                                 WOFNIG5B4D7EB0E9FDD-L    499.0
115326.0                                   MATHUA5AF70A7D1E50A  35599.0

             qty_ordered  grand_total increment_id    category_name_1  \
Customer ID
1.0                  1.0       1950.0    100147443    Women's Fashion
2.0                  1.0        240.0    100147444  Beauty & Grooming
2.0                  1.0        270.0    100222998            Soghaat
3.0                  1.0       2450.0    100147445    Women's Fashion
3.0                  1.0       1245.0    100306394      Men's Fashion
...                  ...          ...          ...                ...
115323.0             1.0      44499.0    100562365         Appliances
115324.0             1.0        549.0    100562376      Men's Fashion
115325.0             1.0        550.0    100562383    Women's Fashion
115325.0             1.0        649.0    100562384    Women's Fashion
115326.0             1.0      35899.0    100562386  Mobiles & Tablets

            sales_commission_code  ...    Year Month Customer Since      M-Y  \
Customer ID                        ...
1.0                            \N  ...  2016.0   7.0         2016-7   7-2016
2.0                            \N  ...  2016.0   7.0         2016-7   7-2016
2.0                            \N  ...  2016.0  11.0         2016-7  11-2016
3.0                            \N  ...  2016.0   7.0         2016-7   7-2016
3.0                            \N  ...  2017.0   5.0         2016-7   5-2017
...                           ...  ...     ...   ...            ...      ...
115323.0                      NaN  ...  2018.0   8.0         2018-8   8-2018
115324.0                      NaN  ...  2018.0   8.0         2018-8   8-2018
115325.0                      NaN  ...  2018.0   8.0         2018-8   8-2018
115325.0                      NaN  ...  2018.0   8.0         2018-8   8-2018
115326.0                      NaN  ...  2018.0   8.0         2018-8   8-2018

               FY  Unnamed: 21  Unnamed: 22 Unnamed: 23 Unnamed: 24  \
Customer ID
1.0          FY17          NaN          NaN         NaN         NaN
2.0          FY17          NaN          NaN         NaN         NaN
2.0          FY17          NaN          NaN         NaN         NaN
3.0          FY17          NaN          NaN         NaN         NaN
3.0          FY17          NaN          NaN         NaN         NaN
...           ...          ...          ...         ...         ...
115323.0     FY19          NaN          NaN         NaN         NaN
115324.0     FY19          NaN          NaN         NaN         NaN
115325.0     FY19          NaN          NaN         NaN         NaN
115325.0     FY19          NaN          NaN         NaN         NaN
115326.0     FY19          NaN          NaN         NaN         NaN

            Unnamed: 25
Customer ID
1.0                 NaN
2.0                 NaN
2.0                 NaN
3.0                 NaN
3.0                 NaN
...                 ...
115323.0            NaN
115324.0            NaN
115325.0            NaN
115325.0            NaN
115326.0            NaN

[1048575 rows x 25 columns]

In [33]:
# Merge different column names
customer_data = orders[['Customer ID']].drop_duplicates()
order_data = orders[['Customer ID', 'item_id']].copy()

customer_data = customer_data.rename(columns={'Customer ID': 'customer_id'})
order_data = order_data.rename(columns={'Customer ID': 'customer_key'})

merged_data = pd.merge(
    customer_data,
    order_data,
    left_on='customer_id',
    right_on='customer_key'
)

print(merged_data)

         customer_id  customer_key   item_id
0                1.0           1.0  211131.0
1                2.0           2.0  211133.0
2                2.0           2.0  324257.0
3                3.0           3.0  211134.0
4                3.0           3.0  473369.0
...              ...           ...       ...
1048570     115323.0      115323.0  905179.0
1048571     115324.0      115324.0  905191.0
1048572     115325.0      115325.0  905200.0
1048573     115325.0      115325.0  905202.0
1048574     115326.0      115326.0  905205.0

[1048575 rows x 3 columns]

In [34]:
# payment methods
print(orders['payment_method'].unique())

payment_counts = orders['payment_method'].value_counts()

print(payment_counts)
print("Highest:", payment_counts.idxmax())

['cod' 'ublcreditcard' 'mygateway' 'customercredit' 'cashatdoorstep'
 'mcblite' 'internetbanking' 'marketingexpense' 'productcredit'
 'financesettlement' 'Payaxis' 'jazzvoucher' 'jazzwallet' 'Easypay'
 'Easypay_MA' 'easypay_voucher' 'bankalfalah' 'apg' nan]
payment_method
cod                  271960
Payaxis               97641
Easypay               82900
jazzwallet            35145
easypay_voucher       31176
bankalfalah           23065
jazzvoucher           15633
Easypay_MA            14028
customercredit         7555
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64
Highest: cod

In [36]:
# product categories
print(orders['category_name_1'].unique())

category_analysis = orders.groupby('category_name_1').agg(
    Orders=('category_name_1', 'count'),
    Quantity_Sold=('qty_ordered', 'sum'),
    Average_Price=('price', 'mean')
)

print(category_analysis)

["Women's Fashion" 'Beauty & Grooming' 'Soghaat' 'Mobiles & Tablets'
 'Appliances' 'Home & Living' "Men's Fashion" 'Kids & Baby' '\\N' 'Others'
 'Entertainment' 'Computing' 'Superstore' 'Health & Sports' 'Books'
 'School & Education' nan]
                    Orders  Quantity_Sold  Average_Price
category_name_1
Appliances           52413        58203.0   11058.435106
Beauty & Grooming    41496        53790.0     879.367090
Books                 1870         2641.0     483.590374
Computing            15933        17251.0   10884.834663
Entertainment        26326        27419.0   19255.987270
Health & Sports      17502        21420.0    1019.756279
Home & Living        26504        30065.0    1130.842838
Kids & Baby          16494        18565.0     672.907624
Men's Fashion        92221       101424.0     907.647622
Mobiles & Tablets   115710       132695.0   17544.771981
Others               29218        84916.0    2224.737901
School & Education    3478         4136.0     482.146144
Soghaat              34011        47418.0     294.215404
Superstore           43613        82542.0     610.781474
Women's Fashion      59721        64216.0    1758.094237
\N                    7850         9647.0    4147.859827

In [37]:
# Create business report
business_report = category_analysis.reset_index()

business_report.columns = [
    'Category',
    'Orders',
    'Quantity Sold',
    'Average Price'
]

print(business_report)

              Category  Orders  Quantity Sold  Average Price
0           Appliances   52413        58203.0   11058.435106
1    Beauty & Grooming   41496        53790.0     879.367090
2                Books    1870         2641.0     483.590374
3            Computing   15933        17251.0   10884.834663
4        Entertainment   26326        27419.0   19255.987270
5      Health & Sports   17502        21420.0    1019.756279
6        Home & Living   26504        30065.0    1130.842838
7          Kids & Baby   16494        18565.0     672.907624
8        Men's Fashion   92221       101424.0     907.647622
9    Mobiles & Tablets  115710       132695.0   17544.771981
10              Others   29218        84916.0    2224.737901
11  School & Education    3478         4136.0     482.146144
12             Soghaat   34011        47418.0     294.215404
13          Superstore   43613        82542.0     610.781474
14     Women's Fashion   59721        64216.0    1758.094237
15                  \N    7850         9647.0    4147.859827

In [38]:
print(business_report)

              Category  Orders  Quantity Sold  Average Price
0           Appliances   52413        58203.0   11058.435106
1    Beauty & Grooming   41496        53790.0     879.367090
2                Books    1870         2641.0     483.590374
3            Computing   15933        17251.0   10884.834663
4        Entertainment   26326        27419.0   19255.987270
5      Health & Sports   17502        21420.0    1019.756279
6        Home & Living   26504        30065.0    1130.842838
7          Kids & Baby   16494        18565.0     672.907624
8        Men's Fashion   92221       101424.0     907.647622
9    Mobiles & Tablets  115710       132695.0   17544.771981
10              Others   29218        84916.0    2224.737901
11  School & Education    3478         4136.0     482.146144
12             Soghaat   34011        47418.0     294.215404
13          Superstore   43613        82542.0     610.781474
14     Women's Fashion   59721        64216.0    1758.094237
15                  \N    7850         9647.0    4147.859827